### ISSUE TITLE
Add support for building el9 packages

### ISSUE THREAD

**Issue by gerrity95** [choria-io/aaasvc#141]
At the moment we can build el7 and el8 compatible packages. We want to also build el9 packages and so, we need to add support to build these and then add them to the nightly builds.

This can be done using the same process as the el8 packages so we can copy the contents from there to generate the new el9 packager

**Comment by ripienaar** [comment]
<img width="1001" alt="Screenshot 2024-03-05 at 17 20 18" src="https://github.com/choria-io/aaasvc/assets/82342/b503e4a8-c243-43a9-992c-b2f66e1b4f17">

Also building after some unrelated issues, will keep open so we can do release next

**Comment by ripienaar** [comment]
Thank you!
